[meta]
name = "Editor Trails"
author = "Miss"
category = "Map Editor"
version = "1.1"
siteid = 251

[script]
dependencies = [ "Camera" ]
optional_dependencies = [ "MLHook", "MLFeedRaceData" ]
exports = [ "Exports.as" ]
